name: Test Build for Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          cd groceryFrontendApp  # Navigate to the project directory
          npm install  # Install dependencies
          npm run build  # Build the project
